# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-context-graph-layer',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-context-graph-layer',
                'lib_path': 'cjm_context_graph_layer'},
  'syms': {}}
