"""Provenance-by-declaration: host logic stays readable Python in the workflow core and DECLARES its provenance contributions as a `Derivation` event node (+ DERIVED_FROM input edges, PRODUCED output edges). This recovers audit completeness without the substrate executing host logic (pass-2 Thread 4's false-dichotomy resolution). The substrate stays untouched: declarations read composition/job ids from the outside.

Docs: https://cj-mills.github.io/cjm-context-graph-layerdeclare.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/declare.ipynb.

# %% auto #0
__all__ = ['Derivation', 'derivation_to_graph']

# %% ../nbs/declare.ipynb #97664d2b
import time
from uuid import uuid4
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .grammar import OverlayRelations, attribution, make_edge

# %% ../nbs/declare.ipynb #c11abbce
@dataclass
class Derivation:
    """One host-logic transformation event, declared for the audit trail.

    Coarse-grained by design: the adopter passes the ids that anchor the event
    (e.g. the Transcript nodes consumed + the Source whose spine was produced),
    not every fine-grained output (per-node provenance already rides each
    node's SourceRefs — duplicating it here would re-create topology, the
    Thread-2 no-derived_from rule).
    """
    actor: str                       # Who ran it (e.g. "host:cjm-transcript-decomp-core")
    method: str                      # The transformation (e.g. "alignment-fold/v1")
    input_ids: List[str] = field(default_factory=list)   # Graph node ids consumed
    output_ids: List[str] = field(default_factory=list)  # Graph node ids produced (coarse anchors)
    asserted_at: Optional[float] = None                  # Unix timestamp; None = now at to_graph time
    composition_id: Optional[str] = None                 # Substrate composition run id, if any
    job_ids: List[str] = field(default_factory=list)     # Member job ids, if any
    properties: Dict[str, Any] = field(default_factory=dict)  # Extra event properties

# %% ../nbs/declare.ipynb #7c77965e
def derivation_to_graph(
    d: Derivation,                       # The declared event
    derivation_id: Optional[str] = None, # Explicit node id; None = generated (events are asserted, not re-derivable)
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:  # (event node wire dict, edges)
    """Materialize a declaration as one event node + DERIVED_FROM / PRODUCED edges.

    The event node gets a GENERATED id (asserted/decision class — the
    FLIP-TRIGGER-protected kind); its edges are deterministic per
    (event, anchor, relation)."""
    node_id = derivation_id or str(uuid4())
    props: Dict[str, Any] = attribution(d.actor, method=d.method, asserted_at=d.asserted_at)
    if d.composition_id:
        props["composition_id"] = d.composition_id
    if d.job_ids:
        props["job_ids"] = list(d.job_ids)
    props.update(d.properties)
    node = {"id": node_id, "label": "Derivation", "properties": props, "sources": []}
    edges = (
        [make_edge(node_id, i, OverlayRelations.DERIVED_FROM, {"role": "input"}) for i in d.input_ids]
        + [make_edge(node_id, o, OverlayRelations.PRODUCED, {"role": "output"}) for o in d.output_ids]
    )
    return node, edges
