"""Deterministic node/edge identity: UUIDv5 over canonical identity tuples (stage-5 ratified rule: a node's id derives from what makes it THE same node across re-derivation, never from its correctable content).

Docs: https://cj-mills.github.io/cjm-context-graph-layeridentity.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/identity.ipynb.

# %% auto #0
__all__ = ['LAYER_ID_NAMESPACE', 'IDENTITY_SEPARATOR', 'canonical_part', 'derive_node_id', 'derive_edge_id']

# %% ../nbs/identity.ipynb #48c3ba87
import uuid
from typing import Union

# %% ../nbs/identity.ipynb #8ae437f7
# Fixed namespace for all context-graph layer ids. Derived once from the DNS
# namespace so the value is stable and reproducible; every deterministic id in
# the ecosystem hangs off this constant.
LAYER_ID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, "context-graph.cj-mills.com")

# Unit separator: cannot appear in paths/hashes/relation names, so joined
# identity parts can never collide across part boundaries.
IDENTITY_SEPARATOR = "\x1f"

# %% ../nbs/identity.ipynb #2f674553
def canonical_part(
    value: Union[str, int, float],  # One identity-tuple part
) -> str:  # Canonical string form used inside the UUIDv5 name
    """Render one identity-tuple part canonically.

    Floats use `repr` (shortest round-trip — identical floats from the same
    deterministic computation render identically); ints use `str`; strings pass
    through. Anything else (including bool, whose int-ness is ambiguous) is
    rejected loudly: identity inputs must be deliberate.
    """
    if isinstance(value, bool):
        raise TypeError("bool is not a valid identity part (ambiguous int)")
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return value
    raise TypeError(f"unsupported identity part type: {type(value).__name__}")

# %% ../nbs/identity.ipynb #cc1d398c
def derive_node_id(
    kind: str,  # Node kind discriminator (e.g. "source", "audio-segment")
    *parts: Union[str, int, float],  # The identity tuple (positional, order-significant)
) -> str:  # Deterministic UUID string (UUIDv5)
    """Derive a deterministic node id from a kind + identity tuple.

    Same kind + same parts always yields the same id, across processes and
    re-derivations — re-derived graphs reproduce their node ids, so cross-graph
    references survive a rebuild (the G3a fix made structural). Content hashes
    belong in SourceRefs, NOT here: identity is position/provenance, never the
    correctable content.
    """
    name = IDENTITY_SEPARATOR.join([kind, *(canonical_part(p) for p in parts)])
    return str(uuid.uuid5(LAYER_ID_NAMESPACE, name))

# %% ../nbs/identity.ipynb #b603404f
def derive_edge_id(
    source_id: str,      # Edge source node id
    target_id: str,      # Edge target node id
    relation_type: str,  # Relation type (e.g. "NEXT")
) -> str:  # Deterministic UUID string
    """Derive a deterministic edge id from (source, target, relation).

    Layer-0 structural edges are unique per (source, target, relation), so the
    triple IS the identity — re-derivation reproduces edge ids the same way it
    reproduces node ids.
    """
    return derive_node_id("edge", source_id, target_id, relation_type)
